---
toc: true
---

## Course Content

The course content, available here, is further enriched by in-class presentations and activities. Each week, we'll engage with the material through:

- Reading assignments introducing key concepts for the unit/topic.
- Followed by lectures, in-class activities, investigations or lab sessions exploring the week's content.
- Submitting _weekly assignments_ through [__Canvas__](https://canvas.calpoly.edu/).

## Weekly Layout

Discover the Weekly Layout — a comprehensive guide to your week's agenda. Access 

lecture slides <i class="fas fa-file-lines"></i>,  
videos <i class="fas fa-video"></i>,    
reading materials <i class="fas fa-book-open"></i>,  
investigations <i class="fa-solid fa-magnifying-glass"></i>   
weekly assignments <i class="fas fa-user"></i> <i class="fas fa-upload"></i>,  
group assignments <i class="fas fa-users"></i> <i class="fas fa-upload"></i> and  
due dates <i class="fas fa-clock"> </i>,  

all conveniently organized for your academic journey.


### {{< fa calendar-days >}} Week 1 (Sep 23 - Sep 26)

<table class="table-striped table-bordered" style="font-size: smaller; text-align: left;">

  <thead>
    <th style="width: 34%">BEFORE CLASS</th>
    <th style="width: 36%">DURING CLASS</th>
    <th style="width: 30%">AFTER CLASS</th>
  </thead>

  <tr>
    <td>&nbsp; Nothing, just come to the class!</td>
    <td>
      &nbsp;<input type="checkbox" /><a href="https://stat218-fall24.github.io/slides/01-Week-01/01-Lect-01/01-welcome.html" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide" target="_blank"></i> Covering the website & syllabus</a> <i class="fas fa-file-lines"></i>   
      &nbsp;<input type="checkbox" /> A Discussion on Life Sci. and Statistics <i class="fas fa-comments"></i>
  <td> 
      &nbsp;<input type="checkbox" /> <a href="https://www.ted.com/talks/hans_rosling_the_best_stats_you_ve_ever_seen" target="_blank"> <i aria-hidden="true" title="External Link to YouTube" target="_blank"></i> The best stats you've ever seen</a> <i class="fas fa-video"></i>  
      &nbsp;<input type="checkbox" /> <a href="https://www.youtube.com/watch?v=Tm2cCnRjcOM&list=PLkIselvEzpM5nFf4nu--q2OGccA_0alYO" target="_blank">
        <i aria-hidden="true" title="External Link to YouTube" target="_blank"></i>Using data to better understand agriculture.</a> <i class="fas fa-video"></i>   
      &nbsp;<input type="checkbox" /><a href="https://www.youtube.com/watch?v=Bz0e5xGDHaU&list=PLkIselvEzpM5nFf4nu--q2OGccA_0alYO" target="_blank">
        <i aria-hidden="true" title="External Link to YouTube" target="_blank"></i>Using statistics to treat chronic illnesses.</a> <i class="fas fa-video"></i> 
<br>

  &nbsp;</i><b> NO SUBMISSION FOR TODAY! </b>
  </td>
</tr>

  <tr>
    <td> &nbsp; <b> CH 1: Introduction </b>  
    &nbsp;<input type="checkbox" /> <b>Section 1.2:</b> Types of Evidence <i class="fas fa-book-open"></i>    
    &nbsp;<input type="checkbox" /> <b>Section 2.1:</b> Introduction to Variables <i class="fas fa-book-open"></i>   

&nbsp; <b>FROM Samuels et al. (2016)</b>
</td>

<td>    
    &nbsp; <input type="checkbox" /><a href="https://docs.google.com/document/d/1DGwqRR4KNm9HNC8UoEsiGz9cw0lUp4XH/copy?usp=sharing&ouid=107969602618040380602&rtpof=true&sd=true" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide" target="_blank"></i> Investigation 1 </a><i class="fa-solid fa-magnifying-glass"></i>   
    </td>
    <td>
    &nbsp;<input type="checkbox" /> <i class="fas fa-users"></i> <i class="fas fa-upload"></i>  Investigation 1  

<br>

<i class="fas fa-clock"></i>  <b> DUE DATE: Thu, Sep 26 </b>
</td>
  </tr>

  <tr>
    <td> &nbsp; <b> CH 1: Introduction </b>  
    <br>
    &nbsp;<input type="checkbox" /> <b>Section 1.3:</b> Random Sampling <i class="fas fa-book-open"></i>    
    
&nbsp; <b>FROM Samuels et al. (2016)</b>
  </td>
    <td>
      &nbsp;&nbsp;<input type="checkbox" /><a href="https://stat218-fall24.github.io/slides/01-Week-01/03-Lect-03/01-sampling.html" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide" target="_blank"></i> Lecture Slides - Sampling </a> <i class="fas fa-file-lines"></i>   
    &nbsp; <input type="checkbox" /> Guided Activity
    </td>

<td>
    &nbsp;<i class="fas fa-user"></i> <i class="fas fa-upload"></i> Weekly Assignment    
    <br>
    &nbsp; <input type="checkbox" /> Exercise 1.2.2     
    &nbsp; <input type="checkbox" /> Exercise 1.2.4     
    &nbsp; <input type="checkbox" /> Exercise 1.2.6        
    &nbsp; <input type="checkbox" /> Exercise 1.3.3 and   
    &nbsp; <input type="checkbox" /> Exercise 2.1.1

<i class="fas fa-clock"></i><b> DUE DATE: Sun, Sep 29</b>
    </td>
  </tr>

  <tr>
    <td>
      &nbsp; <a href="https://rstudio-education.github.io/hopr/starting.html" target="_blank"> <i aria-hidden="true" title="External Link to Book" target="_blank"></i> <b> Introduction to R and RStudio – Lab 1</b></a> <i class="fas fa-book-open"></i>    
      &nbsp; <input type="checkbox" /> Install R <i class="fas fa-download"></i>      
      &nbsp; <input type="checkbox" /> Install RStudio <i class="fas fa-download"></i>  
      &nbsp; <input type="checkbox" /> First Steps in R  
    </td>
    
<td>    
    &nbsp;<input type="checkbox" /><a href="https://stat218-fall24.github.io/slides/01-Week-01/04-Lect-04/01-intro-quarto.html" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide" target="_blank"></i> Lab Slides - Introduction to R & RStudio </a> <i class="fas fa-file-lines"></i>      
    </td>
    <td> 
    &nbsp;<input type="checkbox" /> Upload the PDF file that we created today! </b>    
<br>
    <i class="fas fa-clock"></i><b> DUE DATE: Sun, Sep 29</b>
    </td>
  </tr>

</table>



### {{< fa calendar-days >}} Week 2 (Sep 30 - Oct 03)

<table class="table-striped table-bordered" style="font-size: smaller; text-align: left;">

  <thead>
    <th style="width: 35%">BEFORE CLASS</th>
    <th style="width: 41%">DURING CLASS</th>
    <th style="width: 24%">AFTER CLASS</th>
  </thead>

  <tr>
    <td>
    <b> CH 2: Description of Samples and Populations </b>  
    <br>
    &nbsp;<input type="checkbox" /> <b>Section 2.2:</b> Frequency Distributions <i class="fas fa-book-open"></i>      
    &nbsp;<input type="checkbox" /> <b>Section 2.3:</b> Descriptive Statistics <i class="fas fa-book-open"></i>    

&nbsp; <b>FROM Samuels et al. (2016)</b>  
    </td>
    <td>
      &nbsp;<input type="checkbox" /><a href="https://stat218-fall24.github.io/slides/02-Week-02/01-Lecture-01.html" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide"></i> Lecture Slides - Description of Samples and Populations </a> <i class="fas fa-file-lines"></i>   
      &nbsp;<input type="checkbox" /><a href="https://www.rossmanchance.com/applets/2021/descstats/Dotplot.htm"target="_blank"><i aria-hidden="true" title="External Link to the Applet"></i> Rossman & Chance Applet </a> <i class="fas fa-comments"></i>
  <td>
      &nbsp;<i class="fas fa-user"></i> <i class="fas fa-upload"></i> Weekly Assignment    
    <br>
    &nbsp; <input type="checkbox" /> Exercise 2.2.6     
    &nbsp; <input type="checkbox" /> Exercise 2.3.3     
    &nbsp; <input type="checkbox" /> Exercise 2.3.10        

<i class="fas fa-clock"></i><b> DUE DATE: Sun, Oct, 06</b>
      
  </td>
</tr>

  <tr>
    <td> 
    <b> CH 2: Description of Samples and Populations </b>  
    <br>
    &nbsp;<input type="checkbox" /> <b>Section 2.3:</b> Descriptive Statistics <i class="fas fa-book-open"></i>      
    &nbsp;<input type="checkbox" /> <b>Section 2.6:</b>  Measures of Dispersion <i class="fas fa-book-open"></i>    

&nbsp; <b>FROM Samuels et al. (2016)</b>
</td>

<td>    
    &nbsp; <input type="checkbox" /><a href="https://docs.google.com/document/d/16fyw8B1OubNi8sKx2eXifpq_8rJTz4VF/copy?usp=sharing&ouid=107969602618040380602&rtpof=true&sd=true" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide" target="_blank"></i> Investigation 2 </a><i class="fa-solid fa-magnifying-glass"></i>  
</td>

<td>
    &nbsp;<input type="checkbox" /> <i class="fas fa-users"></i> <i class="fas fa-upload"></i>  Investigation 2  

<br>

<i class="fas fa-clock"></i>  <b> DUE DATE: Thu, Oct 03 </b>
</td>
  </tr>

  <tr>
    <td> 
    &nbsp;   Nothing, just come to the class!	 
    </td>
    <td>
    <br>
     &nbsp; <input type="checkbox" /><a href="https://docs.google.com/presentation/d/1sX9ij32z59iXCRO6LiDC4dG53fKrUEJbLyFfJbzxapQ/edit?usp=sharing" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide" target="_blank"></i> Lecture Slides - Introduction to Chance Models </a> <i class="fas fa-file-lines"></i>   
    &nbsp; <input type="checkbox" /> Guided Activity
    <br>   
    </td>

<td>
&nbsp; <input type="checkbox" /> Review the class notes    
</td>
  </tr>

  <tr>
    <td>
    <b> CH 2: Description of Samples and Populations </b>  
    <br>
    &nbsp;<input type="checkbox" /> <b>Section 2.3:</b> Descriptive Statistics <i class="fas fa-book-open"></i>      
    &nbsp;<input type="checkbox" /> <b>Section 2.6:</b>  Measures of Dispersion <i class="fas fa-book-open"></i>    

&nbsp; <b>FROM Samuels et al. (2016)</b>
    </td>
    
<td>    
    &nbsp; <input type="checkbox" /> <a href="https://stat218-fall24.github.io/slides/02-Week-02/02-Lecture-04/01-Lec-04.html" target="_blank"><i aria-hidden="true" title="External Link to Lab Slide" target="_blank"></i> Lab Slides - Descriptive Statistics - I   </a> <i class="fas fa-file-lines"></i>   
    </td>
    <td> 
    &nbsp;<i class="fas fa-users"></i> <i class="fas fa-upload"></i> Lab Assignment 1  
 
<br>
    <i class="fas fa-clock"></i><b> DUE DATE: Sun, Oct, 06</b>
    </td>
  </tr>

</table>


### {{< fa calendar-days >}} Week 3 (Oct 7 - Oct 10)


<table class="table-striped table-bordered" style="font-size: smaller; text-align: left;">

  <thead>
    <th style="width: 40%">BEFORE CLASS</th>
    <th style="width: 36%">DURING CLASS</th>
    <th style="width: 24%">AFTER CLASS</th>
  </thead>

  <tr>
    <td>
    <b> CHAPTER 3 and CHAPTER 4 </b>  
    <br>
    &nbsp;<input type="checkbox" /> <b>Section 3.1:</b> Probability and the Life Sciences <i class="fas fa-book-open"></i>      
    &nbsp;<input type="checkbox" /> <b>Section 3.2:</b> Introduction to Probability <i class="fas fa-book-open"></i>   
    &nbsp;<input type="checkbox" /> <b>Section 3.4:</b> Density Curves <i class="fas fa-book-open"></i>  
    &nbsp;<input type="checkbox" /> <b>Chapter 4</b> pp. 132- 137 <i class="fas fa-book-open"></i>  

&nbsp; <b>FROM Samuels et al. (2016)</b>  
    </td>
    <td>
      &nbsp;<input type="checkbox" /><a href="https://docs.google.com/presentation/d/1igfbPHLU6WLBQT_yhmyzI8ELFs7ztSi7hxOK-okPqmk/edit?usp=sharing" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide"></i> Lecture Slides </a> <i class="fas fa-file-lines"></i>   
      &nbsp;<input type="checkbox" /><a href="https://www.rossmanchance.com/applets/2021/oneprop/OneProp.htm" target="_blank"><i aria-hidden="true" title="External Link to the Applet"></i> Rossman & Chance Applet </a> <i class="fas fa-comments"></i>
  <td>

<b> No Assignment for today! </b>
      
  </td>
</tr>

  <tr>
    <td> 
    <b> CHAPTER 3 and CHAPTER 4 </b>  
    <br>
    &nbsp;<input type="checkbox" /> <b>Section 3.1:</b> Probability and the Life Sciences <i class="fas fa-book-open"></i>      
    &nbsp;<input type="checkbox" /> <b>Section 3.2:</b> Introduction to Probability <i class="fas fa-book-open"></i>   
    &nbsp;<input type="checkbox" /> <b>Section 3.4:</b> Density Curves <i class="fas fa-book-open"></i>  
    &nbsp;<input type="checkbox" /> <b>Chapter 4</b> pp. 132- 137 <i class="fas fa-book-open"></i>  

&nbsp; <b>FROM Samuels et al. (2016)</b>  
</td>

<td>    
    &nbsp; <input type="checkbox" /><a href="https://docs.google.com/document/d/1lXh19tnJhvO63KAqWkf9_Q9EgcqpAVgR/copy?usp=sharing&ouid=107969602618040380602&rtpof=true&sd=true" target="_blank"><i aria-hidden="true" title="External Link to Investigation document" target="_blank"></i> Investigation 3 </a><i class="fa-solid fa-magnifying-glass"></i>  
</td>

<td>
    &nbsp;<input type="checkbox" /> <i class="fas fa-users"></i> <i class="fas fa-upload"></i>  Investigation 3  

<br>

<i class="fas fa-clock"></i>  <b> DUE DATE: Thu, Oct 10 </b>
</td>
  </tr>

  <tr>
    <td> 
    <b> CH 6: Confidence Intervals </b>  
    <br>
    &nbsp;<input type="checkbox" /> <b>Section 6.1:</b> Statistical Estimation <i class="fas fa-book-open"></i>      
    &nbsp;<input type="checkbox" /> <b>Section 6.2:</b> Standard Error of the Mean <i class="fas fa-book-open"></i>   

&nbsp; <b>FROM Samuels et al. (2016)</b>  
    </td>
    <td>
    <br>
     &nbsp; <input type="checkbox" /><a href="https://docs.google.com/presentation/d/1W7uGk1d0AcO1OU_n83JcUVrZyR0a4IbvKQH838im_wA/edit?usp=sharing" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide" target="_blank"></i> Lecture Slides</a> <i class="fas fa-file-lines"></i>   
    </td>

<td>
    &nbsp;<i class="fas fa-user"></i> <i class="fas fa-upload"></i> Weekly Assignment    
    <br>
    &nbsp; <input type="checkbox" /> Course Survey     


<i class="fas fa-clock"></i><b> DUE DATE: Sun, Oct 13</b> 
</td>
  </tr>

  <tr>
    <td>
    <b> CH 2: Description of Samples and Populations </b>  
    <br>
    &nbsp;<input type="checkbox" /> <b>Section 2.2:</b> Frequency Distributions <i class="fas fa-book-open"></i>      
    &nbsp;<input type="checkbox" /> <b>Section 2.3:</b> Descriptive Statistics <i class="fas fa-book-open"></i>    

&nbsp; <b>FROM Samuels et al. (2016)</b>  
    </td>
    
<td>    
    &nbsp; <input type="checkbox" /> <a href="https://stat218-fall24.github.io/slides/03-Week-03/01-Lecture-04-Lab-02.html" target="_blank"><i aria-hidden="true" title="External Link to Lab Slide" target="_blank"></i> Lab Slides - Descriptive Statistics - II   </a> <i class="fas fa-file-lines"></i>   
    </td>
    <td> 
    &nbsp;<i class="fas fa-users"></i> <i class="fas fa-upload"></i> Lab Assignment 2  
 
<br>
    <i class="fas fa-clock"></i><b> DUE DATE: Sun, Oct, 13</b>
    </td>
  </tr>

</table>


### {{< fa calendar-days >}} Week 4 (Oct 14 - Oct 17)

<table class="table-striped table-bordered" style="font-size: smaller; text-align: left;">

  <thead>
    <th style="width: 40%">BEFORE CLASS</th>
    <th style="width: 36%">DURING CLASS</th>
    <th style="width: 24%">AFTER CLASS</th>
  </thead>

  <tr>
    <td>
    <br>
    <b> Introduction to Confidence Intervals and Quantitative Data</b>  
    <br>    
 Nothing, just come to the class  
    <br>    
    </td>
    </td>
    <td>
      &nbsp;<input type="checkbox" /><a href="https://docs.google.com/presentation/d/1SMEIqdsRczd4xq-64Ayt4i2Nfnc93-A60pgXl_9ajUY/edit?usp=sharing" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide"></i> Lecture Slides - Confidence Intervals </a> <i class="fas fa-file-lines"></i>   
      &nbsp;<input type="checkbox" /><a href="https://www.rossmanchance.com/applets/2021/oneprop/OneProp.htm" target="_blank"><i aria-hidden="true" title="External Link to the Applet"></i> Rossman & Chance Applet </a> <i class="fas fa-comments"></i>
  <td>

<b> No Assignment for today! </b>
      
  </td>
</tr>

  <tr>
    <td> 
    <b> CH 6: INFERENCE FOR CATEGORICAL DATA </b>  
    <br>
    &nbsp;<input type="checkbox" /> <a href="https://leanpub.com/os" target="_blank"><i aria-hidden="true" title="External Link to boook" target="_blank"></i><b>Section 6.1:</b> Inference for a single proportion </a><i class="fas fa-book-open"></i>      

&nbsp; <b>  FROM Diez et al. (2022)</b>  
    </td>
</td>

<td>    
    &nbsp; <input type="checkbox" /><a href="https://docs.google.com/document/d/15nM8QSuxNqc6LPNCDVpmdWdcvXK7KeoX/copy?usp=sharing&ouid=107969602618040380602&rtpof=true&sd=true" target="_blank"><i aria-hidden="true" title="External Link to Investigation document" target="_blank"></i> Investigation 4 -  Climate Change and Confidence Interval </a><i class="fa-solid fa-magnifying-glass"></i>  
</td>

<td>
    &nbsp;<input type="checkbox" /> <i class="fas fa-users"></i> <i class="fas fa-upload"></i>  Investigation 4  

<br>

<i class="fas fa-clock"></i>  <b> DUE DATE: Thu, Oct 17 </b>
</td>
  </tr>

  <tr>
    <td> 
    <b> CH 6: Confidence Intervals </b>  
    <br>
    &nbsp;<input type="checkbox" /> <b>Section 6.1:</b> Statistical Estimation <i class="fas fa-book-open"></i>      
    &nbsp;<input type="checkbox" /> <b>Section 6.2:</b> Standard Error of the Mean <i class="fas fa-book-open"></i>   
    &nbsp;<input type="checkbox" /> <b>Section 6.3:</b> Confidence Interval for µ <i class="fas fa-book-open"></i>  
    &nbsp;<input type="checkbox" /> <b>Section 6.4:</b> Planning a Study to Estimate µ <i class="fas fa-book-open"></i>  

&nbsp; <b>FROM Samuels et al. (2016)</b>  
    </td>
    <td>
    <br>
     &nbsp; <input type="checkbox" /><a href="https://stat218-fall24.github.io/slides/04-Week-04/03-Lecture-03.html" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide" target="_blank"></i> Lecture Slides - Confidence Interval for a Single Mean</a> <i class="fas fa-file-lines"></i>   
    </td>

<td>
    &nbsp;<i class="fas fa-user"></i> <i class="fas fa-upload"></i> Weekly Assignment    
    <br>
    &nbsp; <input type="checkbox" /> See Canvas     


<i class="fas fa-clock"></i><b> DUE DATE: Sun, Oct 20</b> 
</td>
  </tr>

  <tr>
    <td>
    <b> CHAPTER 1 - CHAPTER 6 </b>  
    <br>
    &nbsp;<input type="checkbox" /> Review all chapters <i class="fas fa-book-open"></i>  

&nbsp; <b>FROM Samuels et al. (2016)</b>  
    </td>
    
<td>    
    &nbsp; <input type="checkbox" /> <a href="https://forms.gle/LwNZvKwfWah8BEDn6" target="_blank"><i aria-hidden="true" title="External Link to Lab Slide" target="_blank"></i> Ungraded Quiz - Google Form  </a> <i class="fas fa-highlighter"></i>   
    </td>
    <td> 
    &nbsp; <input type="checkbox" /> Review your class notes
 
<br>
    </td>
  </tr>

</table>

### {{< fa calendar-days >}} Week 5 (Oct 21 - Oct 24)

<table class="table-striped table-bordered" style="font-size: smaller; text-align: left;">

  <thead>
    <th style="width: 35%">BEFORE CLASS</th>
    <th style="width: 40%">DURING CLASS</th>
    <th style="width: 25%">AFTER CLASS</th>
  </thead>

  <tr>
    <td> 
    &nbsp; <b> Ch 6: Confidence Interval </b>  
    &nbsp;<input type="checkbox" /> <b>Section 6.3:</b> CI for µ <i class="fas fa-book-open"></i>    
    &nbsp;<input type="checkbox" /> <b>Section 6.4:</b> Planning a Study to Estimate µ <i class="fas fa-book-open"></i>  
    &nbsp;<input type="checkbox" /> <b>Section 6.5:</b> Conditions for Validity of Estimation Methods <i class="fas fa-book-open"></i>    
    &nbsp; FROM Samuels et al. (2016)
    </td>
    <td>    
    &nbsp; <input type="checkbox" /><a href = "https://docs.google.com/presentation/d/10HzG1IP3dnSkQOzZ1KD1Tg7x_nMWfX1lHfEfXq3hcR4/edit?usp=sharing" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slides"></i> Lecture Slides - Factors Affecting CI </a>&nbsp; <i class="fas fa-file-lines"></i>    
    </td>
    
  <td>
       &nbsp;<i class="fas fa-user"></i> <i class="fas fa-upload"></i> Weekly Assignment    
    <br>
    &nbsp; <input type="checkbox" /> Exercise 6.4.1     

<i class="fas fa-clock"></i><b> DUE DATE: Sun, Oct 27</b>
      
</td>
  </tr>
<tr>
  <td colspan="3" style="text-align: center;">&nbsp; <b> Midterm 1 (In-class) </b></td>
</tr>
<tr>
  <td> 
    &nbsp; <b> Ch 6: Inference for Categorical Data </b>    
    &nbsp;<input type="checkbox"><a href = "https://leanpub.com/os" target="_blank"><i aria-hidden="true" title="External Link to Book PDF"></i><b> Sec. 6.2</b> Difference of two proportions</a>&nbsp; <i class="fas fa-book-open"></i>   
    <br>
    &nbsp; FROM Diez et al. (2022) 
    <br>
  </td>
    <td>    
    &nbsp; <input type="checkbox" /><a href = "https://docs.google.com/presentation/d/1CEetlkhGtgq8MLRdFsAB3hF62OU3n6BgY5J4FWZS0YM/edit?usp=sharing" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide"></i> Lecture Slides - Association and Confounding </a> &nbsp; <i class="fas fa-file-lines"></i>       

  &nbsp; <input type="checkbox" /><a href = "https://stat218-fall24.github.io/slides/05-Week-05/01-Lecture-03.html" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide"></i> Lecture Slides - Difference of Two Proportions </a> &nbsp; <i class="fas fa-file-lines"></i>       
    <td>
    &nbsp; **No Assignment for Today!** 
</td>
  </tr>

  <tr>
    <td> 
    &nbsp; <b> Ch 6: Inference for Categorical Data </b>    
    &nbsp;<input type="checkbox"><a href = "https://leanpub.com/os" target="_blank"><i aria-hidden="true" title="External Link to Book PDF"></i><b> Sec. 6.2</b> Difference of two proportions</a>&nbsp; <i class="fas fa-book-open"></i>   
    <br>
    &nbsp; FROM Diez et al. (2022) 
    <br>
    </td>
    
  <td>
     &nbsp; <input type="checkbox" /><a href = "https://www.rossmanchance.com/chance/stat217S22/labs/lab4/lab4_1.html" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide"></i> Lab Activity - Dolphin Therapy (Applet) </a> &nbsp; <i class="fas fa-file-lines"></i>       
    </td>
    <td>
    &nbsp;<input type="checkbox" /> <i class="fas fa-users"></i> <i class="fas fa-upload"></i> Lab Assignment 3  
<br>
<i class="fas fa-clock"></i><b> DUE DATE: Sun, Oct 27 </b>
    </td>
  </tr>

</table>
### {{< fa calendar-days >}} Week 6 (Oct 28 - Oct 31)

<table class="table-striped table-bordered" style="font-size: smaller; text-align: left;">

  <thead>
    <th style="width: 40%">BEFORE CLASS</th>
    <th style="width: 36%">DURING CLASS</th>
    <th style="width: 24%">AFTER CLASS</th>
  </thead>

  <tr>
    <td>
    &nbsp; <b> Ch 6: Inference for Categorical Data </b>    
    &nbsp;<input type="checkbox"><a href = "https://leanpub.com/os" target="_blank"><i aria-hidden="true" title="External Link to Book PDF"></i><b> Sec. 6.2</b> Difference of two proportions</a>&nbsp; <i class="fas fa-book-open"></i>   
    <br>
    &nbsp; <b> FROM Diez et al. (2022) </br>
    <br>
    </td>
    <td>
      &nbsp;<input type="checkbox" /><a href="https://docs.google.com/presentation/d/1_Ec3vnjueEeLCPyBcumGL5KgUlqp8PEoE3Hj-O1RP40/edit?usp=sharing" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide"></i> Lecture Slides - Lab 3 Review - Comparing Two Proportions </a> <i class="fas fa-file-lines"></i>   
  </td>
  <td>
  
<b> No Assignment for today! </b>
      
  </td>
</tr>

  <tr>
    <td> 
    <b> Review these previous lecture slides </b>  
    <br>
    &nbsp; <input type="checkbox" /><a href = "https://docs.google.com/presentation/d/1CEetlkhGtgq8MLRdFsAB3hF62OU3n6BgY5J4FWZS0YM/edit?usp=sharing" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide"></i> Lecture Slides - Association and Confounding </a> &nbsp; <i class="fas fa-file-lines"></i>       

  &nbsp; <input type="checkbox" /><a href = "https://stat218-fall24.github.io/slides/05-Week-05/01-Lecture-03.html" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide"></i> Lecture Slides - Difference of Two Proportions </a> &nbsp; <i class="fas fa-file-lines"></i>       
</td>

<td>    
    &nbsp; <input type="checkbox" /><a href="https://docs.google.com/document/u/1/d/1K6MqctglpgHHqJ7nPHEUNDrfzI3anpA8/copy?usp=sharing&ouid=107969602618040380602&rtpof=true&sd=true" target="_blank"><i aria-hidden="true" title="External Link to Investigation document" target="_blank"></i> Investigation 5 - Do COVID vaccines work?
 </a><i class="fa-solid fa-magnifying-glass"></i>  
</td>

<td>
    &nbsp;<input type="checkbox" /> <i class="fas fa-users"></i> <i class="fas fa-upload"></i>  Investigation 5  

<br>

<i class="fas fa-clock"></i>  <b> DUE DATE: Thu, Oct 31 </b>
</td>
  </tr>

  <tr>
    <td> 
    <b> CH 6: Confidence Intervals </b>  
    <br>
    &nbsp;<input type="checkbox" /> <b>Section 6.6:</b> Comparing two means  <i class="fas fa-book-open"></i>      
    &nbsp;<input type="checkbox" /> <b>Section 6.7:</b> Confidence Interval for µ1 - µ2 <i class="fas fa-book-open"></i>   

&nbsp; <b>FROM Samuels et al. (2016)</b>  
    </td>
    <td>
    <br>
     &nbsp; <input type="checkbox" /><a href="https://stat218-fall24.github.io/slides/06-Week-06/01-Lecture-03.html" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide" target="_blank"></i> Lecture Slides - Comparing Two Means </a> <i class="fas fa-file-lines"></i>   
    </td>

<td>
    &nbsp;<i class="fas fa-user"></i> <i class="fas fa-upload"></i> Weekly Assignment    
    <br>
    &nbsp; <input type="checkbox" /> Course Survey     


<i class="fas fa-clock"></i><b> DUE DATE: Sun, Nov 03</b> 
</td>
  </tr>

  <tr>
    <td>
   &nbsp; <b> Ch 7: Inference for Numerical Data </b>    
    &nbsp;<input type="checkbox"><a href = "https://leanpub.com/os" target="_blank"><i aria-hidden="true" title="External Link to Book PDF"></i> 7.1.5 One sample t-tests</a>&nbsp; <i class="fas fa-book-open"></i>    
    &nbsp; FROM Diez et al. (2022)   
  <br>    
  <b> CH 6: Confidence Intervals </b>  
    <br>
    &nbsp;<input type="checkbox" /> <b>Section 6.6:</b> Comparing two means  <i class="fas fa-book-open"></i>      
    &nbsp;<input type="checkbox" /> <b>Section 6.7:</b> Confidence Interval for µ1 - µ2 <i class="fas fa-book-open"></i>   

&nbsp; <b>FROM Samuels et al. (2016)</b>  
    </td>
    
<td>    
    &nbsp; <input type="checkbox" /> <a href="https://stat218-fall24.github.io/slides/06-Week-06/02-Lecture-04-Lab-04.html" target="_blank"><i aria-hidden="true" title="External Link to Lab Slide" target="_blank"></i> Lab Slides - Applications of t-tests   </a> <i class="fas fa-file-lines"></i>   
    </td>
    <td> 
    &nbsp;<i class="fas fa-users"></i> <i class="fas fa-upload"></i> Lab Assignment 4  
 
<br>
    <i class="fas fa-clock"></i><b> DUE DATE: Sun, Nov, 03</b>
    </td>
  </tr>

</table>


### {{< fa calendar-days >}} Week 7 (Nov 4 - Nov 7)

<table class="table-striped table-bordered" style="font-size: smaller; text-align: left;">

  <thead>
    <th style="width: 37%">BEFORE CLASS</th>
    <th style="width: 33%">DURING CLASS</th>
    <th style="width: 30%">AFTER CLASS</th>
  </thead>

  <tr>
    <td> 
    <br>
    &nbsp; <b> Ch 8: Comparison of Paired Samples </b>  
    &nbsp;<input type="checkbox"> <b>Section 8.1:</b> Introduction <i class="fas fa-book-open"></i>  
    &nbsp;<input type="checkbox"> <b>Section 8.2:</b> The Paired-Sample t Test and Confidence Interval <i class="fas fa-book-open"></i>  
    &nbsp;<input type="checkbox"> <b> Section 8.3:</b> The Paired Design  <i class="fas fa-book-open"></i>  
    &nbsp; FROM Samuels et al. (2016)    
    </td>
    <td> 
    &nbsp; <input type="checkbox" /><a href = "https://docs.google.com/presentation/d/1E6BOgp_l08zvHcN2sV_XHtYaJOJH7cf6REP-EaxQ0uc/edit?usp=sharing"target="_blank"><i aria-hidden="true" title="External Link to Lecture Slides"></i> Lecture Slides - The Paired Design </a> &nbsp; <i class="fas fa-file-lines"></i>   
    </td>
    <td>
   &nbsp;<i class="fas fa-user"></i> <i class="fas fa-upload"></i> Weekly Assignment 
   
   <input type="checkbox">Week 6 & 7 Review Assignment (CANVAS)     

    <i class="fas fa-clock"></i><b> DUE DATE: Sun, Nov 10 </b>  
  </td>
</tr>

  <tr>
    <td> 
    <br>
    &nbsp; <b> Ch 8: Comparison of Paired Samples </b>  
    &nbsp;<input type="checkbox"> <b>Section 8.1:</b> Introduction <i class="fas fa-book-open"></i>  
    &nbsp;<input type="checkbox"> <b>Section 8.2:</b> The Paired-Sample t Test and Confidence Interval <i class="fas fa-book-open"></i>  
    &nbsp;<input type="checkbox"> <b> Section 8.3:</b> The Paired Design  <i class="fas fa-book-open"></i>  
    &nbsp; FROM Samuels et al. (2016)    
    </td>
<td>    
    &nbsp; <input type="checkbox" /><a href="https://docs.google.com/document/d/1ZqjMkmX2LLEAsBPUpmwtO3RRNKyXMOJ8/copy?usp=sharing&ouid=107969602618040380602&rtpof=true&sd=true" target="_blank"><i aria-hidden="true" title="External Link to Investigation document" target="_blank"></i> Investigation 6 - Document
 </a><i class="fa-solid fa-magnifying-glass"></i>  
</td>

<td>
    &nbsp;<input type="checkbox" /> <i class="fas fa-users"></i> <i class="fas fa-upload"></i>  Investigation 6  

<br>

<i class="fas fa-clock"></i>  <b> DUE DATE: Fri, Nov 08 </b>
</td>
  </tr>
<tr>
  <td colspan="3" style="text-align: center;">    &nbsp;<input type="checkbox" /> <i class="fas fa-users"></i> <i class="fas fa-upload"></i> <b> Midterm 2 Due Date Today (Take Home) </b></td>
</tr>
  <tr>
  <td>
    <br>
    &nbsp; <b> Ch 8: Comparison of Paired Samples </b>  
    &nbsp;<input type="checkbox"> <b>Section 8.1:</b> Introduction <i class="fas fa-book-open"></i>  
    &nbsp;<input type="checkbox"> <b>Section 8.2:</b> The Paired-Sample t Test and Confidence Interval <i class="fas fa-book-open"></i>  
    &nbsp;<input type="checkbox"> <b> Section 8.3:</b> The Paired Design  <i class="fas fa-book-open"></i>  
    &nbsp; FROM Samuels et al. (2016) 
    </td>
    <td>    
     &nbsp;<input type="checkbox" /><a href="https://stat218-fall24.github.io/slides/07-Week-07/01-Lec-04-Lab-05.html" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide" target="_blank"></i> Lab Slides - Paired Samples t-test </a> &nbsp; <i class="fas fa-file-lines"></i>
    </td>
    <td> 
    &nbsp;<i class="fas fa-users"></i> <i class="fas fa-upload"></i> Lab Assignment 5  
 
<br>
    <i class="fas fa-clock"></i><b> DUE DATE: Sun, Nov, 10</b>    </td>
  </tr>
</table>

### {{< fa calendar-days >}} Week 8 (Nov 12 - Nov 14)

<table class="table-striped table-bordered" style="font-size: smaller; text-align: left;">

  <thead>
    <th style="width: 45%">BEFORE CLASS</th>
    <th style="width: 30%">DURING CLASS</th>
    <th style="width: 25%">AFTER CLASS</th>
  </thead>

<tr>
  <td colspan="3" style="text-align: center;">&nbsp; <b> Cal Poly Holiday (No class meeting) </b></td>
</tr>
  <tr>
    <td>
    &nbsp; Comprehensive Review of Weeks 1-7   
    &nbsp; <input type="checkbox" /> <b> Bring your midterm papers if you had (I'll distribute them if you did not get) </b>
    </td>   
    <td>    
    &nbsp; <input type="checkbox" /> Reviewed midterm questions &nbsp; &nbsp; <i class="fas fa-highlighter"></i> 
    </td>
    <td>  
<b> No Assignment for today! </b>
    </td>  
    </tr>
  <tr>
    <td>
    &nbsp; <b>Ch 6: Inference for Categorical Data</b>  
    &nbsp;<input type="checkbox"><a href = "https://leanpub.com/os" target="_blank"><i aria-hidden="true" title="External Link to Book PDF"></i><b> Sect. 6.3</b> Testing for goodness of fit using chi-square</a>&nbsp; <i class="fas fa-book-open"></i>   
    &nbsp;<input type="checkbox"><a href = "https://leanpub.com/os" target="_blank"><i aria-hidden="true" title="External Link to Book PDF"></i><b> Sect. 6.4 </b> Testing for independence in two-way tables</a>&nbsp;<i class="fas fa-book-open"></i>   
    &nbsp;&nbsp;FROM Diez et al. (2022)   
    </td>   
    <td>    
    &nbsp; <input type="checkbox"><a href="https://docs.google.com/presentation/d/1DZCOirVJ_tPuhr59VhRlDFk9ZpsKCqEO32mYyfcJO5Q/edit?usp=sharing" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide"></i> Lecture Slides - Chi Square Test </a> &nbsp; <i class="fas fa-file-lines"></i>    
    </td>
    <td>
<b> No assignment for today! </b>   
    </td> 
    </tr>
  <tr>
    <td> 
    &nbsp; <b>Ch 6: Inference for Categorical Data</b>  
    &nbsp;<input type="checkbox"><a href = "https://leanpub.com/os" target="_blank"><i aria-hidden="true" title="External Link to Book PDF"></i><b> Sect. 6.3</b> Testing for goodness of fit using chi-square</a>&nbsp; <i class="fas fa-book-open"></i>   
    &nbsp;<input type="checkbox"><a href = "https://leanpub.com/os" target="_blank"><i aria-hidden="true" title="External Link to Book PDF"></i><b> Sect. 6.4 </b> Testing for independence in two-way tables</a>&nbsp;<i class="fas fa-book-open"></i>   
    &nbsp;&nbsp;FROM Diez et al. (2022)   
    </td>
    <td> 
    &nbsp; <input type="checkbox" /><a href="https://docs.google.com/document/d/1TrrLLVs_IrYSP88aL-tfmcWczbFsQfyz/copy?usp=sharing&ouid=107969602618040380602&rtpof=true&sd=true" target="_blank"><i aria-hidden="true" title="External Link to Investigation document" target="_blank"></i> Investigation 7 - Comparing Multiple Proportions
 </a><i class="fa-solid fa-magnifying-glass"></i>  
</td>
    </td>
    <td>
     &nbsp;<input type="checkbox" /> <i class="fas fa-users"></i> <i class="fas fa-upload"></i> Investigation 7    
    <br>
    <i class="fas fa-clock"></i><b> DUE DATE: Sun, Nov 17 </b>
    </td> 
    </tr>

</table>



### {{< fa calendar-days >}} Week 9 (Nov 18 - Nov 21)

<table class="table-striped table-bordered" style="font-size: smaller; text-align: left;">

  <thead>
    <th style="width: 42%">BEFORE CLASS</th>
    <th style="width: 35%">DURING CLASS</th>
    <th style="width: 23%">AFTER CLASS</th>
  </thead>

<tr>
    <td>
    &nbsp; <b> Ch 11: Comparing the Means of Many Independent Samples </b>    
    &nbsp;<input type="checkbox"> <b> Sec. 11.1</b> Introduction &nbsp; <i class="fas fa-book-open"></i>   
    &nbsp;<input type="checkbox"> <b> Sec. 11.2</b> The Basic One-Way ANOVA &nbsp; <i class="fas fa-book-open"></i>   
    &nbsp;<input type="checkbox"> <b> Sec. 11.4</b> The Global F Test &nbsp; <i class="fas fa-book-open"></i>   
    &nbsp;<input type="checkbox"> <b> Sec. 11.5</b> Applicability of Methods &nbsp; <i class="fas fa-book-open"></i> 
    <br>
    &nbsp; FROM Samuels et al. (2016)
    <br>
    </td>   
    <td>    
    &nbsp; <input type="checkbox"><a href="https://docs.google.com/presentation/d/1SbttWuyJuL-tYlblgNMsFPfzPF8q1RilWK4mTLc38SY/edit?usp=sharing" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide"></i> Lecture Slides - Introduction to One Way ANOVA </a> &nbsp; <i class="fas fa-file-lines"></i>   
    </td>
    <td>
     &nbsp;<input type="checkbox" /> <i class="fas fa-user"></i> <i class="fas fa-upload"></i> Week 9 Individual Assignment (on CANVAS)
    <br>
    <i class="fas fa-clock"></i><b> DUE DATE: Sun, Nov 24 </b>
    </td> 
</tr>
  <tr>
    <td>
    &nbsp; <b> Ch 11: Comparing the Means of Many Independent Samples </b>    
    &nbsp;<input type="checkbox"> <b> Sec. 11.1</b> Introduction &nbsp; <i class="fas fa-book-open"></i>   
    &nbsp;<input type="checkbox"> <b> Sec. 11.2</b> The Basic One-Way ANOVA &nbsp; <i class="fas fa-book-open"></i>   
    &nbsp;<input type="checkbox"> <b> Sec. 11.4</b> The Global F Test &nbsp; <i class="fas fa-book-open"></i>   
    &nbsp;<input type="checkbox"> <b> Sec. 11.5</b> Applicability of Methods &nbsp; <i class="fas fa-book-open"></i> 
    <br>
    &nbsp; FROM Samuels et al. (2016)
    <br>
    </td>   
    <td>    
   &nbsp; <input type="checkbox" /><a href = "https://docs.google.com/document/d/1szD8jxR6lyqOUlsl5JmwBIw00pLEyZj3YkQAw-fYfAg/copy?usp=sharing" target="_blank"><i aria-hidden="true" title="External Link to Lab Worksheet"></i> Investigation 8 - Comparing Multiple Means</a>&nbsp; <i class="fa-solid fa-magnifying-glass"></i>  
    </td>
    <td>
    <br>
     &nbsp;<input type="checkbox" /> <i class="fas fa-users"></i> <i class="fas fa-upload"></i> Investigation 8   
    <br>
    <i class="fas fa-clock"></i><b> DUE DATE: Thu, Nov 21 </b>
    </td> 
    </tr>
  <tr>
    <td>
    &nbsp; <b> Ch 11: Comparing the Means of Many Independent Samples </b>    
    &nbsp;<input type="checkbox"> <b> Sec. 11.6</b> One-Way Randomized Blocks Design &nbsp; <i class="fas fa-book-open"></i>   
    <br>
    &nbsp; FROM Samuels et al. (2016)
    <br>
    </td>   
    <td>    
   &nbsp; <input type="checkbox" /><a href = "https://stat218-fall24.github.io/slides/09-Week-09/01-Lecture-01.html" target="_blank"><i aria-hidden="true" title="External Link to Lab Worksheet"></i> Lecture Slides - One Way Randomized Blocks Design </a>&nbsp; <i class="fas fa-file-lines"></i>  
    </td>
    <td>
     &nbsp;<input type="checkbox" /> <i class="fas fa-user"></i> <i class="fas fa-upload"></i> Extra Credit (on CANVAS)
    <br>
    <i class="fas fa-clock"></i><b> DUE DATE: Thu, Nov 21 </b>    
    </td> 
    </tr>
  <tr>
    <td>     
    &nbsp; <b> Ch 11: Comparing the Means of Many Independent Samples </b>    
    &nbsp;<input type="checkbox"> <b> Sec. 11.1</b> Introduction &nbsp; <i class="fas fa-book-open"></i>   
    &nbsp;<input type="checkbox"> <b> Sec. 11.2</b> The Basic One-Way ANOVA &nbsp; <i class="fas fa-book-open"></i>   
    &nbsp;<input type="checkbox"> <b> Sec. 11.4</b> The Global F Test &nbsp; <i class="fas fa-book-open"></i>   
    &nbsp;<input type="checkbox"> <b> Sec. 11.5</b> Applicability of Methods &nbsp; <i class="fas fa-book-open"></i> 
    <br>
    &nbsp; FROM Samuels et al. (2016)
    <br>
    </td>   
    <td>    
    &nbsp; <input type="checkbox" /><a href = "https://drive.google.com/file/d/1quhp-ARRlU3-oezK9E6rdBSOIkmmohb5/view?usp=sharing"  target="_blank"><i aria-hidden="true" title="External Link to Lab Dataset"></i> Lab Dataset - Aldrin Concentration </a>&nbsp; <i class="fas fa-laptop-file"></i>      
    &nbsp; <input type="checkbox" /><a href = "https://stat218-fall24.github.io/slides/09-Week-09/04-Lecture-04/01-Lec-04-Lab-06.html" target="_blank"><i aria-hidden="true" title="External Link to Lab Slide"></i> Lab Slides - One-Way ANOVA </a> &nbsp; <i class="fas fa-file-lines"></i>     
    </td>
    <td>
    <br>
     &nbsp;<input type="checkbox" /> <i class="fas fa-users"></i> <i class="fas fa-upload"></i> Lab Assignment 6  
    <br>
    <i class="fas fa-clock"></i><b> DUE DATE: Sun, Nov 24 </b>    </td> 
    </tr>

</table>


### {{< fa calendar-days >}} Week 10 (Dec 2 -Dec 5)

<table class="table-striped table-bordered" style="font-size: smaller; text-align: left;">

  <thead>
    <th style="width: 40%">BEFORE CLASS</th>
    <th style="width: 37%">DURING CLASS</th>
    <th style="width: 23%">AFTER CLASS</th>
  </thead>

<tr>
    <td>
          &nbsp; <b> Ch 12: Linear Regression and Correlation </b>    
    &nbsp;<input type="checkbox"> <b> Sec. 12.1</b> Introduction &nbsp; <i class="fas fa-book-open"></i>   
    &nbsp;<input type="checkbox"> <b> Sec. 12.2</b> The Correlation Coefficient &nbsp; <i class="fas fa-book-open"></i>   
    <br>
    &nbsp; FROM Samuels et al. (2016)
    <br>
    </td>   
    <td>    
    &nbsp; <input type="checkbox"><a href="https://docs.google.com/presentation/d/1ditBAP-1zslL4cl0tfiUWXdfzEU1P3eb1iAn8NCaVjo/edit?usp=sharing" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide"></i> Lecture Slides - Correlation </a> &nbsp; <i class="fas fa-file-lines"></i>   
    </td>
    <td>
    <b> No assignment for today </b>
    </td> 
</tr>
  <tr>
    <td>
    &nbsp; <b> Ch 12: Linear Regression and Correlation </b>    
    &nbsp;<input type="checkbox"> <b> Sec. 12.3</b> The Fitted Regression Line &nbsp; <i class="fas fa-book-open"></i>   
    &nbsp;<input type="checkbox"> <b> Sec. 12.4</b> Parametric Interpretation of Regression: The Linear Model &nbsp; <i class="fas fa-book-open"></i>    
    &nbsp;<input type="checkbox"> <b> Sec. 12.5</b> Statistical Inference Concerning $\beta_1$ &nbsp; <i class="fas fa-book-open"></i>   
    <br>
    &nbsp; FROM Samuels et al. (2016) 
    </td>   
    <td>    
   &nbsp; <input type="checkbox" /><a href = "https://docs.google.com/presentation/d/15Q1CLS0WsGLYNaSWk9fLHsjYIO8cpGuMxOHX0Nm-Y3s/edit?usp=sharing" target="_blank"><i aria-hidden="true" title="External Link to Lab Worksheet"></i> Lecture Slides - 
   Bivariate Regression </a>&nbsp; <i class="fas fa-file-lines"></i>  
    </td>
    <td>
    <br>
     &nbsp;<input type="checkbox" /> <i class="fas fa-user"></i> <i class="fas fa-upload"></i> Week 10 Individual Assignment (on CANVAS)
    <br>
    <i class="fas fa-clock"></i><b> DUE DATE: Fri, Dec 06 </b>
    </td> 
    </tr>
  <tr>
    <td>
      &nbsp; <b> Ch 12: Linear Regression and Correlation </b>    
    &nbsp;<input type="checkbox"> <b> Sec. 12.1</b> Introduction &nbsp; <i class="fas fa-book-open"></i>   
    &nbsp;<input type="checkbox"> <b> Sec. 12.2</b> The Correlation Coefficient &nbsp; <i class="fas fa-book-open"></i>   
        &nbsp;<input type="checkbox"> <b> Sec. 12.3</b> The Fitted Regression Line &nbsp; <i class="fas fa-book-open"></i>   
    &nbsp;<input type="checkbox"> <b> Sec. 12.4</b> Parametric Interpretation of Regression: The Linear Model &nbsp; <i class="fas fa-book-open"></i>    
    &nbsp;<input type="checkbox"> <b> Sec. 12.5</b> Statistical Inference Concerning $\beta_1$ &nbsp; <i class="fas fa-book-open"></i>   
    <br>
    &nbsp; FROM Samuels et al. (2016)
    <br>
    </td>   
    <td>    
    &nbsp; <input type="checkbox" /><a href = "" target="_blank"><i aria-hidden="true" title="External Link to Lecture Slide"></i> Lab Slides - Coming Soon!</a> &nbsp; <i class="fas fa-file-lines"></i>       
    </td>
    <td>
    <br>
     &nbsp;<input type="checkbox" /> <i class="fas fa-users"></i> <i class="fas fa-upload"></i> Lab Assignment 7  
    <br>
    <i class="fas fa-clock"></i><b> DUE DATE: Fri, Dec 6 </b>    
    </td> 
    </tr>
  <tr>
    <td>     
ALL CHAPTERS!
    </td>   
    <td>    
    &nbsp; <input type="checkbox" /> <a href="" target="_blank"><i aria-hidden="true" title="External Link to Lab Slide" target="_blank"></i> Ungraded Quiz - Google Form  </a> <i class="fas fa-highlighter"></i>   
    </td>
    <td> 
    &nbsp; <input type="checkbox" /> Review your class notes
 
<br>
    </td>
    </tr>

</table>
